gravitee-io/gravitee-kubernetes-operator

.github/renovate.json

Renovate still does not use the commit convention

ci: add semantic commits option to renovate

---

controllers/apim/apidefinition/internal/delegate.go
controllers/apim/apidefinition/internal/delete.go
controllers/apim/apidefinition/internal/update.go
controllers/apim/apidefinition/internal/update_api_state.go

As having a management context does not implie being connected to mapi this seems more appropriate (eg, the context could point to a bad url)

refactor: rename has management context method

---

Makefile
scripts/k3d.mjs

Install ginkgo before running test. It will allow any new contributor to run the tests without having to install ginkgo manually in the bin directory
Add the flag to allow the gateway to listen to all namespaces

test: listen all namespaces

---

test/apidefinition_controller_create_test.go
test/apidefinition_controller_delete_test.go
test/apidefinition_controller_error_test.go
test/apidefinition_controller_plan_and_subscription_test.go
test/apidefinition_controller_start_stop_test.go
test/apidefinition_controller_udpate_test.go
test/apiresource_controller_update_test.go

This is to avoid the smoke test becoming flaky because of errors reported in our logs during test execution.

test: ensure context is created before creating api

---

controllers/apim/apidefinition/apidefinition_controller.go
internal/utils/zap.go
main.go

The dev mode will allow us to pass from something like
```
1.67032314137655e+09    INFO    All workers finished    {"controller": "apiresource", "controllerGroup": "gravitee.io", "controllerKind": "ApiResource"}
1.67032314137655e+09    INFO    All workers finished    {"controller": "managementcontext", "controllerGroup": "gravitee.io", "controllerKind": "ManagementContext"}
1.670323141376551e+09   INFO    Shutdown signal received, waiting for all workers to finish     {"controller": "ingress", "controllerGroup": "networking.k8s.io", "controllerKind": "Ingress"}
1.670323141376686e+09   INFO    All workers finished    {"controller": "ingress", "controllerGroup": "networking.k8s.io", "controllerKind": "Ingress"}
```
to
```json
{"level":"info","ts":1670323158.854773,"msg":"Stopping and …
```

feat: add DEV_MODE logging option

---

README.adoc
helm/gko/templates/NOTES.txt

- Mention in helm note that the operator is still in beta
- Remove prerelease references 
- add go report badge

docs: mention alpha in helm note

---

config/samples/ingress/ingress-with-multiple-hosts.yml
config/samples/ingress/ingress-without-api-template.yml
scripts/k3d.mjs
test/ingress_controller_create_test.go
test/internal/constants.go

https://gravitee.atlassian.net/browse/APIM-784
Run k3d using the APIM Gatweay as a LoadBalancer service.
Now when you apply the example ingress-with-multiple-hosts.yml the gateway should respond if you do the following call for example `curl -i http://localhost:9001/httpbin/get --header "Host: httpbin.example.com"`

Deploy gateway as LB

---

.github/workflows/sync-branches.yml

Now we can trigger the sync manually we need to configure git email and user name before running the commands

ci: add user and email in sync-branches

---

api/v1alpha1/managementcontext_types.go
controllers/apim/apidefinition/apidefinition_controller.go
controllers/apim/apidefinition/watchers.go
controllers/apim/managementcontext/internal/delete.go
controllers/apim/managementcontext/internal/update.go
controllers/apim/managementcontext/managementcontext_controller.go
internal/search/search.go
main.go
pkg/keys/keys.go
test/internal/fixtures.go
test/managementcontext_controller_delete_test.go
test/suite_test.go

When a context path is linked to an api definition it should not be removable. It a user remove it, it becomes really difficult for them to remove tha apidefinition as they wont have access to the context to call APIM

refactor: context not removable when linked to api definition

---

test/apidefinition_controller_create_test.go
test/apidefinition_controller_delete_test.go
test/apidefinition_controller_error_test.go
test/apidefinition_controller_plan_and_subscription_test.go
test/apidefinition_controller_start_stop_test.go
test/apidefinition_controller_udpate_test.go
test/apiresource_controller_update_test.go
test/suite_test.go

At the beginning of the project some licenses has certainly been added manually. Now we can use the command `make add-license` to do it. In some files the is useless licenses.

test: remove and lint tests licenses

---

.circleci/config.yml
helm/gko/README.md
helm/gko/templates/bundle-config.yaml
helm/gko/templates/bundle.yaml
helm/gko/tests/bundle-config_test.yaml
helm/gko/values.yaml
internal/env/env.go
main.go

This is to circumvent the fact that helm does not re-apply the crds directory on updates.

feat: patch resource definitions on startup

---

.circleci/config.yml

Since all the checks are performed before merging the release branch, this step is not required

ci: remove test chart from release workflow

---

helm/gko/templates/bundle-config.yaml
helm/gko/tests/bundle-config_test.yaml

Otherwise, the namespace is not set when rendering the chart with `helm template`
see https://gravitee.atlassian.net/browse/APIM-2450

fix: set config namespace to release namespace

---

.gitignore
config/manager/manager.yaml
docs/api/reference.md
helm/gko/crds/api-definition.yaml
helm/gko/templates/bundle.yaml
helm/gko/tests/bundle-config_test.yaml

This is so that when a user updates its config and run a helm upgrade, the manager rolls out and load the config changes
see https://gravitee.atlassian.net/browse/APIM-2713

fix: rollout on helm upgrades when config changes

---

.circleci/config.yml

As we don't use the release namespace and release name to name the cluster roles any more, the CI now deploys using a different service account name for each NS

ci: fix helm chart deployment

---

test/application_controller_create_test.go
test/application_controller_update_test.go
test/ingress_controller_delete_test.go

I think we could also get rid of the create test, as the create is done in the update (the code is exactly the same until update kicks in)

test: add status expectation to fix flaky test

---

helm/gko/templates/manager/deployment.yaml

the annotation was forgotten in the process of moving to full helm instead of the kustomize / helm mix.

chore(helm): restore checksum annotation on manager

---

helm/gko/README.md
helm/gko/templates/manager/config.yaml
helm/gko/values.yaml
make/dev.mk
make/doc.mk
make/tool.mk

Bitnami readme generator allow to organise Helm documentation into sections, which makes the document somehow more readable.
⚠️ To keep sections consistants, the `httpClient` value has been moved to the manager section.
Which means this should be released in 1.0.0 only and documented as a breaking change.

docs(helm): use bitnami readme generator

---

api/model/api/base/api.go
api/model/api/v2/api.go

There is no point into having this field in the spec as we have no control over it. Will be kept in v1alpha1 as it has been here from day 1, but will be removed from v1beta1.
Note: For v1beta1 its would be a useful info to put in our status.

refactor: move deployed at to v2

---

internal/watch/watch.go

Because the management context secret namespace is not mandatory, we need to set it when queuing a reconcile, otherwise the latest version of controller runtime will throw an error if listening to a single namespace.
```
error	Reconciler error	{"controller": "secret", "controllerGroup": "", 
"controllerKind": "Secret", "Secret": {"name":"apim-context-credentials"}, "namespace": "", 
"name": "apim-context-credentials", "reconcileID": "c4b8729d-7924-4db7-99e5-5734bd311427", 
"error": "unable to get: /apim-context-credentials because of unknown namespace for the cache"}
```

fix: ensure ns is set on context secret requests

---

api/model/api/base/api.go
api/v1alpha1/apidefinition_types.go
controllers/apim/ingress/internal/api_definition_template.go
test/apidefinition_controller_create_test.go

This flag may be replaced in v1beta1 and might not be available first because the v2 REST API is not ready for this yet
see https://gravitee.atlassian.net/browse/APIM-2427

refactor: move the `local` flag from base to v1alpha1

---

controllers/apim/ingress/internal/mapper/mapper.go

⚠️ Requires apim 3.20.27 - 4.0.16 - 4.1.7 - 4.2.1 as an ingress runtime.

fix: allow support for http2 requests on ingresses

---

api/v1alpha1/managementcontext_types.go
helm/gko/crds/gravitee.io_managementcontexts.yaml

We do not need to add `name` as a custom column as it is added by default.

fix: do not print context name column twice

---

api/model/api/base/plan.go
api/model/api/v2/plan.go
api/model/api/v4/api.go
api/model/api/v4/plan.go
api/v1alpha1/apidefinitionv4_types.go
controllers/apim/ingress/internal/api_definition_template.go
docs/api/reference.md
examples/apim/api_definition/api-v4-with-context.yml
examples/apim/api_definition/api-v4.yml
helm/gko/crds/gravitee.io_apidefinitionv4s.yaml
kind/kind.yaml
test/integration/apidefinition/update_withoutContext_asTemplate_test.go

This is to clearly state the difference between plan map keys, and the name property
see https://gravitee.atlassian.net/browse/GKO-21
relies on https://github.com/gravitee-io/gravitee-api-management/pull/7231

refactor: rename plan crd name to displayName

---

helm/gko/README.md
helm/gko/values.yaml

see https://github.com/gravitee-io/issues/issues/9818

fix: bump default version of kube rbac proxy to 0.18.0

---

.circleci/config.yml

Now that we support several branch, we cannot just use latest anymore.

ci: use exact tag in release link for slack notif

---

test/integration/apidefinition/create_withContext_MemberWithoutRole_test.go
test/integration/apidefinition/update_withContext_changingMemberRole_test.go

This will add 2 tests for member in v2 APIs ([GKO-331](https://gravitee.atlassian.net/browse/GKO-331)):
- should change the role of an API member
- should change the role of an API member
**It's automating the following manual tests**
[GKO-308](https://gravitee.atlassian.net/browse/GKO-308)
[GKO-393](https://gravitee.atlassian.net/browse/GKO-393)
[GKO-331]: https://gravitee.atlassian.net/browse/GKO-331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GKO-308]: https://gravitee.atlassian.net/browse/GKO-308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GKO-393]: https://gravitee.atlassian.net/browse/GKO-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

adding tests for member in v2 APIs

---

api/model/api/base/page.go
docs/api/reference.md
helm/gko/crds/gravitee.io_apidefinitions.yaml
helm/gko/crds/gravitee.io_apiv4definitions.yaml

This is required to be able to configure a multi file fetcher.

fix: add `ROOT` type to page types

---

api/model/refs/namespace.go
api/v1alpha1/apiv2definition_types.go
api/v1alpha1/apiv2definition_webhook.go
api/v1alpha1/apiv4definition_types.go
api/v1alpha1/apiv4definition_webhook.go
api/v1alpha1/application_types.go
api/v1alpha1/application_webhook.go
internal/admission/common/mutate/context.go
pkg/types/k8s/custom/custom.go
test/integration/admissionwebhook/api_v2_mutate_withContext_withoutNamespace.go
test/integration/admissionwebhook/api_v4_mutate_withContext_withoutNamespace.go
test/integration/admissionwebhook/application_mutate_withContext_withoutNamespace.go

see https://gravitee.atlassian.net/browse/GKO-320
From now on the contest ref namespace will default to the resource namespace if not specified.

feat: make context ref namespace optional

---

test/integration/ingress/create_withoutContext_andMultipleHosts_test.go

For some reason, this test does not pass if we run it with the withContext setup.
Given that the ingress controller feature is not a priority at the moment, we skip this test and will investigate later on this.

ci: skip ingress test with multiple host and context

---

test/integration/apidefinition/v4/create_withContext_andOneCategory_test.go
test/integration/apidefinition/v4/update_withContext_createMultipleCategoriesAndDeleteOne_test.go
test/internal/integration/apim/export.go

This PR adds the following:
- with a single category
- with multiple categories and the ability to remove a category (update)
* Added a new method `V4Api` to the `Export` service to export v4 API definitions
https://gravitee.atlassian.net/browse/GKO-721

test: add category tests for v4 APIs

---

api/model/api/base/member.go
test/integration/apidefinition/v4/create_withContext_andMemberWithoutRole_test.go
test/integration/apidefinition/v4/update_withContext_changingMemberRole_test.go
test/integration/apidefinition/v4/update_withContext_removingMember_test.go
test/internal/integration/assert/assert.go

* Check the default role assignment for a member without a role
* Verify the role change of an API member
* Verify the removal of an API member
* [`api/model/api/base/member.go`](diffhunk://#diff-c8e2d1ab38c7d4633f896849376f427f638115f9e9abee49a81bb7e218076116L37-R38): Removed the `DisplayName` field from the `String` method of the `Member` struct.
* [`test/integration/apidefinition/v2/update_withContext_removingMember_test.go`](diffhunk://#diff-07ec1003528bd10bf40a6be5c59017b6e0f1183cba54104b7461b49be7aa0adbL66-R66): Updated test descriptions to reflect changes in the number of members being checked. [[1]](diffhunk://#diff-07ec1003528bd10bf40a6be5c59017b6e0f1183cba54104b7461b49be7aa0adbL66-R66) [[2]](diffhunk://#diff-07ec1003528bd10bf40a6be5c59017b6e0f1183cba54104b7461b49be7aa0adbL88-R88) …

test: add member tests for v4 APIs

---

internal/admission/subscription/validate.go
test/integration/admission/subscription/create_withContext_and_syncFromKubernetes_test.go

see https://gravitee.atlassian.net/browse/GKO-809
There was an inversion in the formater param, making what is supposed to look like
`unable to subscribe to API [apim-apim-master/ct-category-v2] because its definition is not synced from the management API (sourcing subscriptions from a Kubernetes cluster is not supported at the moment)`
looking like 
`unable to subscribe to API [sourcing subscriptions from a Kubernetes cluster is not supported at the moment] because its definition is not synced from the management API (apim-apim-master/ct-category-v2)`

fix: enhance error message in submission admission

---

scripts/run-kind.mjs

This PR includes a small change to the `scripts/run-kind.mjs` file. The change adds a new endpoint for the Gateway with mTLS to the list of available endpoints.

test: add mTLS option to run-kind script output

---

test/e2e/chainsaw/commands/callGateway.mjs
test/e2e/chainsaw/tests/v2api/create-update-delete/chainsaw-test.yaml

To improve the efficiency of test runs I replaced the fixed sleep command with a more dynamic retry mechanism.
Now, for example, the create-update-delete test only needs around 19s (before: 49s)
Enhancement summary:
* Added retry logic to the `callGateway.mjs` script
* Removed sleep command to eliminate unnecessary waiting time

test: adding retries to callGateway script

---

.circleci/config.yml
test/e2e/chainsaw/commands/callGateway.mjs
test/e2e/chainsaw/config.yaml

This PR includes several changes to the CI/CD pipeline and end-to-end (E2E) testing configuration to enable Chainsaw to start E2E tests.
- Added Azure login setup
- Updates to the Chainsaw test configuration
https://gravitee.atlassian.net/browse/GKO-1108

test: setup circleci to run chainsaw e2e tests

---

test/e2e/chainsaw/commands/createServiceAccount.mjs
test/e2e/chainsaw/tests/apis/changingMemberRole/v2/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/changingMemberRole/v4/chainsaw-test.yaml

This PR adds new end-to-end Chainsaw tests to verify that API member roles can be changed for both v2 and v4 APIs.
**New Chainsaw E2E tests for member role changes:**
* Added `chainsaw-test.yaml` for v2 APIs to test creating an API with a service account member, updating the member's role, and verifying the exported API YAML reflects the change.
* Added `chainsaw-test.yaml` for v4 APIs with similar steps as v2, including creation, role update, and export verification for member roles.
**New service account creation command:**
* Added `createServiceAccount.mjs` script to automate creation of service account users for use in E2E tests.
See: https://gravitee.atlassian.net/browse/GKO-1372

test: add e2e test for changing member role

---

test/e2e/chainsaw/tests/apis/managementContext_badCredentials/v2/api-with-bad-credentials-ctx.yaml
test/e2e/chainsaw/tests/apis/managementContext_badCredentials/v2/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/managementContext_badCredentials/v2/context-bad-credentials.yaml
test/e2e/chainsaw/tests/apis/managementContext_badCredentials/v4/api-with-bad-credentials-ctx.yaml
test/e2e/chainsaw/tests/apis/managementContext_badCredentials/v4/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/managementContext_badCredentials/v4/context-bad-credentials.yaml
test/e2e/chainsaw/tests/apis/managementContext_reconcileBadUrl/v2/api-with-bad-url-ctx.yaml
test/e2e/chainsaw/tests/apis/managementContext_reconcileBadUrl/v2/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/managementContext_reconcileBadUrl/v2/context-bad-url.yaml
test/e2e/chainsaw/tests/apis/managementContext_reconcileBadUrl/v4/api-with-bad-url-ctx.yaml
test/e2e/chainsaw/tests/apis/managementContext_reconcileBadUrl/v4/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/managementContext_reconcileBadUrl/v4/context-bad-url.yaml
test/integration/apidefinition/v2/create_withWrongContext_test.go
test/integration/apidefinition/v4/create_withWrongContext_test.go

This PR adds new e2e Chainsaw tests to verify v2 and v4 APIs and Management Context creation failure scenarios when the context is using:
1. Bad credentials
2. Bad URL 
- ERROR for invalid management context credentials
> admission webhook "v1alpha1.gravitee.io.managementcontext" denied the request: bad credentials for context [...]
-  ERROR for missing management context
> admission webhook "v1alpha1.gravitee.io.apidefinition" denied the request: resource [...] references management context [...] that doesn't exist in the cluster
- ERROR when deploying APIs with context using a bad URL
> admission webhook "v1alpha1.gravitee.io.apiv4definition" denied the request: unable to perform request [PUT] http://localhost:8083/management/v2/organizations/DEFAULT/environments/DEFAULT/apis/_import/crd …

test: add e2e tests for bad management context

---

test/e2e/README.md

This PR adds documentation for running E2E tests for GKO. The new `test/e2e/README.md` guides users through setup, execution, and best practices for authoring E2E tests using Kyverno Chainsaw.
See: https://gravitee.atlassian.net/browse/GKO-1415

test: adds README.md to the e2e directory

---

test/e2e/README.md
test/e2e/chainsaw/config.yaml
test/e2e/chainsaw/tests/apis/startStopApi/v2/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/startStopApi/v2/v2-started-api.yaml
test/e2e/chainsaw/tests/apis/startStopApi/v2/v2-stopped-api.yaml
test/e2e/chainsaw/tests/apis/startStopApi/v4/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/startStopApi/v4/v4-started-api.yaml
test/e2e/chainsaw/tests/apis/startStopApi/v4/v4-stopped-api.yaml
test/e2e/chainsaw/tests/setup/chainsaw-test.yaml
test/integration/apidefinition/v2/start_withContext_test.go
test/integration/apidefinition/v2/stop_withContext_test.go
test/integration/apidefinition/v4/start_withContext_test.go
test/integration/apidefinition/v4/stop_withContext_test.go

This PR migrates the API start/stop tests for both v2 and v4 definitions from the integration test suite to the e2e test suite, adds new Chainsaw-based e2e tests for these scenarios, and updates setup and tooling instructions for running tests. 
See:
- https://gravitee.atlassian.net/browse/GKO-1405
- https://gravitee.atlassian.net/browse/GKO-1406

test: add e2e test for starting a stopped v2 API

---

test/e2e/chainsaw/tests/apis/localFalse/v2/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/localFalse/v2/v2-api-with-local-false.yml
test/e2e/chainsaw/tests/apis/localFalse/v4/chainsaw-test.yaml
test/e2e/chainsaw/tests/apis/localFalse/v4/v4-api-with-local-false.yml
test/integration/apidefinition/v2/create_withContext_andLocalFalse_test.go
test/integration/apidefinition/v4/create_withContext_andLocalFalse_test.go

This PR migrates integration tests for APIs with `local: false` (`syncFrom: MANAGEMENT` for v4)  from the integration test suite to the e2e test suite. 
See: https://gravitee.atlassian.net/browse/GKO-1482

E2e local false test

---

hack/scripts/generate-changelog.mjs

During last APIM / GKO releases, change log generation failed. 
Apparently there is a breaking change in Jira REST API v3 that leads to an error when we query Jira to get the support issues that should be included in the change log.
This PR replicates what as been done for APIM in https://github.com/gravitee-io/gravitee-api-management/pull/13225 in our release pipeline.

ci: fix jira query for changelog generation

---

examples/apim/api_definition/v4/api-v4-with-shared-endpoint-configuration.yml

We had a question coming from a user about the shared configuration object

docs: add example of api v4 with shared endpoint config
