gravitee-io/gravitee-kubernetes-operator

README.adoc
Update and format read me file
=> docs: update read me

.circleci/config.yml
In order to pass through the first release ...
=> ci: disable lint on release

README.adoc
DOC-248 Updated readme to state clearly that the current release is BETA
=> DOC-248 Updated readme

.circleci/config.yml
This step is know performed by the k3d script
=> ci: remove wait step from test job

api/model/api.go, config/crd/bases/gravitee.io_apidefinitions.yaml, docs/api/reference.md
https://graviteecommunity.atlassian.net/browse/APIM-298
Make metadata value optional
=> fix: make metadata value optional

README.adoc
=> docs: update read me commands

config/samples/context/dev/management-context-with-secret-ref.yml, controllers/apim/apidefinition/internal/update.go, internal/apim/managementapi/apis.go, internal/apim/managementapi/clienterror/not_found.go, internal/apim/managementapi/model/api.go, scripts/k3d.mjs, test/apidefinition_controller_udpate_test.go
see https://gravitee.atlassian.net/browse/APIM-15
=> feat: set definition context on create and updates

.circleci/config.yml
we figured out this while doing the 3.15.22 release
=> ci: notify release only when step passes

config/samples/apim/api-with-context.yml, config/samples/apim/api-with-endpoint-groups.yml, config/samples/apim/api-with-health-check-disabled.yml, config/samples/apim/api-with-health-check.yml, config/samples/apim/api-with-logging.yml, config/samples/apim/api-with-no-plan.yml, config/samples/apim/api-with-service-discovery.yml, config/samples/apim/basic-api.yml, controllers/apim/apidefinition/internal/delegate.go, controllers/apim/apidefinition/internal/helper.go, controllers/apim/apidefinition/internal/update.go, test/apidefinition_controller_plan_and_subscription_test.go, test/internal/constants.go
issue: https://gravitee.atlassian.net/browse/APIM-544
=> fix: remove automatic plan creation

.circleci/config.yml, .gitignore, config/manager/manager.yaml, helm/gko/Chart.yaml, helm/gko/README.md, helm/gko/README.md.gotmpl, helm/gko/tests/bundle_test.yaml, helm/gko/values.yaml, make/doc.mk, make/helm.mk, make/lint.mk, make/test.mk, make/tool.mk, release.config.js, scripts/helm-release.mjs
The goal of the P.R. is to
- generate the legacy `bundle.yml` file on releases in order to allow users that have already installed this way to upgrade without breaking anything
- set chart version according to the release version
- generate chart reference on release
=> ci: enhance helm release

.github/workflows/sync-branches.yml
=> ci: add missing quote in sync-branches

.github/workflows/sync-branches.yml
Remove token usage in gh action sync-branches
=> ci: remove token usage during sync-branches

.circleci/config.yml
Deploy the operator in the new LoadBalancer Gateway namespace
=> ci: deploy manager in apim-master-lb-gateway namespace

.circleci/config.yml
After the last updates on cloud apim the gateway will finally be deployed only on master
=> ci: revert commit 3a45de24

controllers/apim/managementcontext/internal/delete.go, controllers/apim/managementcontext/internal/update.go, controllers/apim/managementcontext/managementcontext_controller.go
Resolve minor bugs with Management Context controller
=> fix: resolve few bug

scripts/k3d.mjs, scripts/util/docker.mjs, scripts/util/env.mjs, scripts/util/helm.mjs, scripts/util/k3d.mjs
Here is a proposition to split the k3d script which begins to be a little bit complex
=> split k3d script

controllers/apim/apidefinition/apidefinition_controller.go, controllers/apim/apidefinition/internal/status.go, controllers/apim/managementcontext/managementcontext_controller.go, internal/indexer/indexer.go, internal/search/search.go
looks like ci lint is a bit stricter in its latest version :)
=> refactor: fix lint issues

config/samples/apim/api-resource-cache-redis.yml, config/samples/apim/api-resource-cache.yml, config/samples/apim/api-resource-http-auth-provider.yml, config/samples/apim/api-resource-inline-auth-provider.yml, config/samples/apim/api-resource-keycloak-adapter.yml, config/samples/apim/api-resource-ldap-auth-provider.yml, config/samples/apim/api-resource-oauth2-am.yml, config/samples/apim/api-resource-oauth2-generic.yml
The local flag has been added everywhere in the apis samples even in the api resources 🙈
=> fix: remove local flag on ApiResource

config/samples/apim/basic-api-templating.yml, controllers/apim/apidefinition/apidefinition_controller.go, controllers/apim/apidefinition/internal/delegate.go, controllers/apim/apiresource/apiresource_controller.go, controllers/apim/application/application_controller.go, controllers/apim/application/internal/delegate.go, controllers/apim/ingress/ingress_controller.go, controllers/apim/ingress/internal/delegate.go, controllers/apim/managementcontext/managementcontext_controller.go, internal/env/template/resolver.go, pkg/keys/keys.go, scripts/k3d.mjs, scripts/util/env.mjs, scripts/util/k3d.mjs, test/apidefinition_controller_create_test.go, test/internal/constants.go
https://gravitee.atlassian.net/browse/APIM-1584
=> feat: template resolver

internal/env/env.go, internal/http/http.go
**Issue:**
https://gravitee.atlassian.net/browse/APIM-2393
=> fix: allow insecure skip verify in HTTPClient

.circleci/config.yml, bundle.yml, config/manager/kustomization.yaml, config/manager/manager.yaml, helm/gko/README.md, helm/gko/templates/bundle.yaml, helm/gko/values.yaml, make/dev.mk, make/docker.mk, make/helm.mk, scripts/helm-release.mjs
see https://gravitee.atlassian.net/browse/APIM-1524
=> feat: allow custom manager image and tag

api/model/type.go, config/samples/apim/basic-api-with-rate-limit.yml, test/apidefinition_controller_create_test.go, test/internal/constants.go
https://github.com/gravitee-io/issues/issues/9260
=> fix: unmarshal int values in GenericMap

api/model/plan.go, config/crd/bases/gravitee.io_apidefinitions.yaml, config/samples/apim/basic-api-with-disabled-policy.yml, docs/api/reference.md, test/apidefinition_controller_create_test.go, test/internal/constants.go
https://gravitee.atlassian.net/browse/APIM-2464
=> fix: let users disable flow-steps

helm/gko/templates/bundle.yaml
Update kube-rbac-proxy version
=> fix: update kube-rbac-proxy version

bundle.yml, config/default/manager_auth_proxy_patch.yaml, helm/gko/README.md, helm/gko/crds/api-definition.yaml, helm/gko/templates/bundle-config.yaml, helm/gko/templates/bundle.yaml, helm/gko/values.yaml
https://gravitee.atlassian.net/browse/APIM-2825
=> Kube rbac proxy

helm/gko/templates/manager/config.yaml, main.go, make/dev.mk
see https://gravitee.atlassian.net/browse/APIM-2970
see https://github.com/gravitee-io/issues/issues/9292
=> fix(helm): avoid conflicting type in manager config map

controllers/apim/apidefinition/apidefinition_controller.go, controllers/apim/apidefinition/internal/deploy.go, controllers/apim/apidefinition/internal/update.go
Issue:
https://gravitee.atlassian.net/browse/APIM-3059
=> fix: enable/disable api when it is not local

api/model/api/base/http.go, config/crd/bases/gravitee.io_apidefinitions.yaml, docs/api/reference.md, helm/gko/crds/gravitee.io_apidefinitions.yaml
https://gravitee.atlassian.net/browse/APIM-3850
=> fix: remove omitempty for some fields

.circleci/config.yml
tested on the ci staging branch, the image is imported to snyk as expected
=> fix: snyk integration

api/model/api/v2/api.go, api/v1alpha1/apidefinition_types.go, api/v1alpha1/apiv4definition_types.go, docs/api/reference.md, helm/gko/crds/gravitee.io_apidefinitions.yaml, test/integration/apidefinition/create_withContext_fromExport_test.go
see https://gravitee.atlassian.net/browse/GKO-195
=> fix: set syncFrom property on API reconcile

api/model/api/v4/plan.go, docs/api/reference.md, helm/gko/crds/gravitee.io_apiv4definitions.yaml
see https://gravitee.atlassian.net/browse/GKO-235
=> fix: add general conditions to v4 plan

helm/gko/README.md, helm/gko/templates/manager/deployment.yaml, helm/gko/values.yaml
see https://github.com/gravitee-io/issues/issues/9819
=> feat: make image pull policies configurables in helm chart

api/model/api/v2/endpoints.go, api/model/api/v2/services.go, docs/api/reference.md, helm/gko/crds/gravitee.io_apidefinitions.yaml
see https://gravitee.atlassian.net/browse/GKO-319
=> fix: remove status from v2 endpoint and fix service model

README.adoc
fixed broken doc links since we overhauled the GKO docs
=> docs: update README.md

api/model/application/application.go, api/model/application/zz_generated.deepcopy.go, api/v1alpha1/application_types.go, controllers/apim/application/internal/update.go, docs/api/reference.md, examples/apim/application/application.yml, helm/gko/crds/gravitee.io_applications.yaml, internal/apim/model/application.go, internal/apim/service/applications.go
see: https://gravitee.atlassian.net/browse/GKO-276
=> refactor: sync using new application crd endpoint

api/model/application/application.go, docs/api/reference.md, helm/gko/crds/gravitee.io_applications.yaml
see https://gravitee.atlassian.net/browse/GKO-346
=> fix: persist false values for application disabled membership notif

examples/apim/api_definition/v2/api-with-page-swagger-http-fetcher.yml, examples/apim/api_definition/v4/api-v4-with-page-swagger-http-fetcher.yml
see https://gravitee.atlassian.net/browse/GKO-347
=> docs: fix fetcher examples

api/model/api/v2/api.go, docs/api/reference.md, helm/gko/crds/gravitee.io_apidefinitions.yaml
see: https://gravitee.atlassian.net/browse/GKO-394
=> feat: allow users to choose the API execution_mode

api/v1alpha1/apiv4definition_webhook.go, api/v1alpha1/managementcontext_types.go, api/v1alpha1/managementcontext_webhook.go, internal/webhook/certs.go, main.go, test/integration/admissionwebhook/api_v4_create_withContext_missing_context_webhook_test.go, test/integration/admissionwebhook/api_v4_create_withContext_webhook_test.go, test/integration/admissionwebhook/api_v4_create_withoutContext_invalid_path_webhook_test.go, test/integration/admissionwebhook/api_v4_update_withContext_missing_context_webhook_test.go, test/integration/admissionwebhook/api_v4_update_withoutContext_invalid_path_webhook_test.go, test/integration/admissionwebhook/managementcontext_create_missing_reference_webhook_test.go, test/integration/admissionwebhook/managementcontext_create_missing_secret_webhook_test.go, test/integration/admissionwebhook/managementcontext_create_unavailable_apim_webhook_test.go, test/integration/admissionwebhook/managementcontext_update_missing_secret_webhook_test.go, test/integration/admissionwebhook/managementcontext_update_unavailable_apim_webhook_test.go, test/integration/admissionwebhook/webhook_generate_secretes_withoutContext.go, test/integration/admissionwebhook/webhook_patch_admission_webhook_configuration_withoutContext.go
see: https://gravitee.atlassian.net/browse/GKO-321
=> feat: add validation webhook to GKO

internal/admission/api/v4/validate.go, test/integration/admission/apiV4_create_withoutContext_andNoPlans_test.go, test/integration/admission/apiV4_update_withoutContext_andNoPlans_test.go
see: https://gravitee.atlassian.net/browse/GKO-423
=> feat: add API plan validation

.golangci.yml, api/model/application/application.go, controllers/apim/ingress/internal/secret.go, docs/api/reference.md, helm/gko/crds/gravitee.io_applications.yaml, internal/indexer/indexer.go
see https://github.com/gravitee-io/issues/issues/9963 
see https://gravitee.atlassian.net/browse/GKO-549
=> fix: make application description required

internal/admission/api/base/paths.go, test/integration/admission/api/v2/create_withoutContext_andConflictingPath_test.go
see https://gravitee.atlassian.net/browse/GKO-595
=> fix: clean paths before looking for conflict

.circleci/config.yml
see https://gravitee.atlassian.net/browse/GKO-522
=> ci: integrate with aqua sec

api/v1alpha1/apiv2definition_types.go
see https://gravitee.atlassian.net/browse/GKO-632
see https://gravitee.atlassian.net/browse/GKO-633
=> refactor: ensure api definition context

api/model/api/base/plan.go, api/model/api/v2/plan.go, api/model/api/v4/plan.go, controllers/apim/ingress/internal/api_definition_template.go, docs/api/reference.md, helm/gko/crds/gravitee.io_apiv4definitions.yaml, test/integration/apidefinition/v2/update_withoutContext_asTemplate_test.go
see: https://gravitee.atlassian.net/browse/GKO-9
=> fix: make plan description optional

.circleci/config.yml
see https://gravitee.atlassian.net/browse/GKO-610
=> ci: deploy only 4.5.x on staging

helm/gko/README.md, helm/gko/templates/manager/deployment.yaml, helm/gko/tests/manager/deployment_test.yaml, helm/gko/values.yaml
see https://gravitee.atlassian.net/browse/GKO-713
see https://github.com/gravitee-io/issues/issues/10092
=> fix: allow to set image pull secrets using helm

test/integration/apidefinition/v2/create_withContext_andMultipleGroups_test.go, test/integration/apidefinition/v2/create_withContext_andOneGroup_test.go
Adding tests for groups in v2 APIs. 
- Add 1 group 
- add multiple groups 
- delete group
https://gravitee.atlassian.net/browse/GKO-716
=> adding tests for groups in v2 APIs

helm/gko/templates/rbac/resource-patch-cluster-role.yaml
see https://gravitee.atlassian.net/browse/GKO-749
=> refactor: narrow down rbac for webhook updates

helm/gko/templates/manager/deployment.yaml
set tolerations for gko-controller-manager
=> set tolerations for gko-controller-manager

test/integration/apidefinition/v4/create_withContext_andOneGroup_test.go, test/integration/apidefinition/v4/update_withContext_createMultipleGroupsAndDeleteOne_test.go, test/internal/integration/apim/export.go
**This PR adds new test cases for v4 APIs:**
- with a single group (API creation)
- with multiple groups and the ability to remove a group (API update)
https://gravitee.atlassian.net/browse/GKO-717
=> test: add group tests for v4 APIs

test/integration/apidefinition/v2/create_withContext_andMardownPage_test.go, test/integration/apidefinition/v2/create_withContext_andSwaggerHTTPFetcher_test.go, test/integration/apidefinition/v2/update_withContext_andMardownPage_test.go, test/integration/apidefinition/v2/update_withContext_deletingPage_test.go
see https://gravitee.atlassian.net/browse/GKO-761
=> test: fix integration tests for pages

examples/usecase/subscribe-to-jwt-plan/README.md
This pull request includes several minor improvements and corrections to the `examples/usecase/subscribe-to-jwt-plan/README.md` file.
=> docs: fix typos in usecase README.md

api/v1alpha1/apiv2definition_types.go
see: https://gravitee.atlassian.net/browse/GKO-804
=> fix: 2 or more API plans of the same type will be create in APIM

internal/admission/subscription/validate.go
see https://gravitee.atlassian.net/browse/GKO-802
=> fix: set expected OAUTH plan type to OAUTH2

api/model/subscription/subscription.go, api/v1alpha1/subscription_types.go, controllers/apim/subscription/internal/update.go, internal/admission/subscription/validate.go, internal/core/interface.go, test/integration/admission/subscription/create_withContext_and_invalidEndingAt_test.go, test/integration/admission/subscription/update_withContext_and_invalidEndingAt_test.go
see https://gravitee.atlassian.net/browse/GKO-806
=> fix: validate end date in subscription admission

internal/admission/subscription/validate.go, test/integration/admission/subscription/create_withContext_and_syncFromKubernetesV2_test.go, test/integration/admission/subscription/create_withContext_and_unknownPlanV2_test.go
see https://gravitee.atlassian.net/browse/GKO-810
=> fix: resolve panic in subscription admission

controllers/apim/subscription/internal/update.go
see https://gravitee.atlassian.net/browse/GKO-813
=> fix: use rfc constant for time formater

api/v1alpha1/apiv2definition_types.go, docs/api/reference.md, helm/gko/crds/gravitee.io_apidefinitions.yaml
see https://gravitee.atlassian.net/browse/GKO-814
=> fix: set local false by default for v2 APIs

api/model/api/base/status.go, api/model/application/status.go, api/v1alpha1/apiv2definition_types.go, api/v1alpha1/apiv4definition_types.go, api/v1alpha1/application_types.go, controllers/apim/subscription/internal/delete.go, controllers/apim/subscription/internal/update.go, docs/api/reference.md, examples/apim/api_definition/v2/api-with-jwt-plan.yml, examples/apim/subscription/subscription.yml, helm/gko/crds/gravitee.io_apidefinitions.yaml, helm/gko/crds/gravitee.io_apiv4definitions.yaml, helm/gko/crds/gravitee.io_applications.yaml, internal/admission/api/base/validate.go, internal/admission/api/v2/ctrl.go, internal/admission/api/v2/validate.go, internal/admission/api/v4/ctrl.go, internal/admission/api/v4/validate.go, internal/admission/application/ctrl.go, internal/admission/application/validate.go, internal/core/interface.go, internal/indexer/indexer.go, internal/k8s/dynamic/apis.go, test/integration/admission/api/v2/delete_withContext_andSubscription_test.go, test/integration/admission/api/v2/update_withContext_andUnknownMember_test.go, test/integration/admission/api/v2/update_withContext_deletingSubscribedPlan_test.go, test/integration/admission/api/v4/delete_withContext_andSubscription_test.go, test/integration/admission/api/v4/update_withContext_deletingSubscribedPlan_test.go, test/integration/admission/application/delete_withContext_andSubscription_test.go, test/integration/usecase/subscribe_withContext_andJWT_v2_test.go
see https://gravitee.atlassian.net/browse/GKO-812
=> feat: avoid deletion of resources involved in a subscription

controllers/apim/apidefinition/internal/api_resources.go, controllers/apim/apidefinition/internal/delegate.go
https://gravitee.atlassian.net/browse/GKO-830
=> fix: resolve template strings on resource references

api/v1alpha1/apiv2definition_types.go, api/v1alpha1/apiv4definition_types.go, api/v1alpha1/application_types.go, controllers/apim/apidefinition/controller.go, controllers/apim/apidefinition/internal/delete.go, controllers/apim/application/application_controller.go, controllers/apim/application/internal/delete.go, controllers/apim/subscription/internal/delete.go, controllers/apim/subscription/subscription_controller.go
see https://gravitee.atlassian.net/browse/GKO-850
=> fix: maintain subscription count on updates

internal/search/assert.go, test/integration/admission/managementcontext/delete_withRef_test.go
see https://gravitee.atlassian.net/browse/GKO-872
=> fix: enhance management context admission error

api/model/api/base/plan.go, api/model/api/v2/services.go, docs/api/reference.md, helm/gko/crds/gravitee.io_apidefinitions.yaml, helm/gko/crds/gravitee.io_apiv4definitions.yaml
see https://gravitee.atlassian.net/browse/GKO-897
=> fix: add deprecated plan status

internal/admission/mctx/default.go, test/integration/admission/managementcontext/defaults_withCloudSecretRef_test.go, test/unit/admission/mctx/mctx_default.go
see https://gravitee.atlassian.net/browse/GKO-923
=> fix: don't append path in cloud context url defaulter

api/model/api/v4/api.go, api/v1alpha1/apiv4definition_types.go, internal/admission/api/v4/shared_policy_group.go, internal/admission/api/v4/validate.go, internal/indexer/indexer.go
see: https://gravitee.atlassian.net/browse/GKO-978
=> fix: add API V4 admission validation for SPG

test/integration/admission/api/v4/create_withContext_andMissingSharedPolicyGroup_test.go
see: https://gravitee.atlassian.net/browse/GKO-978
=> refactor: add API V4 admission validation for SPG

internal/admission/api/v4/shared_policy_group.go, test/integration/admission/api/v4/create_withContext_andWrongSharedPolicyGroupPhase_test.go, test/internal/integration/constants/constants.go
see: https://gravitee.atlassian.net/browse/GKO-988
=> fix: check FlowStep phase and SPG phase before applying CRD

internal/template/tree.go
see https://gravitee.atlassian.net/browse/GKO-1034
=> fix: ommit status and metadata when compiling templates

helm/gko/templates/rbac/admission-webhook-cluster-role.yaml
see https://gravitee.atlassian.net/browse/GKO-1043
=> fix: grant access to webhook cert to webhook role

.gitignore, test/e2e/chainsaw/.chainsaw.yaml, test/e2e/chainsaw/commands/callGateway.mjs, test/e2e/chainsaw/tests/v2api/create-update-delete/chainsaw-test.yaml, test/e2e/chainsaw/tests/v2api/create-update-delete/keyless-v2.yaml
This PR introduces a E2E testing framework called Chainsaw, and also includes configurations and a first test scenario for creating, updating, and deleting a v2 API resource.
https://gravitee.atlassian.net/browse/GKO-1100
=> test: add e2e test framework chainsaw and a first test

examples/apim/api_definition/v2/api-with-jwt-plan.yml
see https://gravitee.atlassian.net/browse/GKO-997
=> docs: improve jwt v2 api example

controllers/gateway-api/httproute/internal/mapper/filters.go, controllers/gateway-api/httproute/internal/mapper/redirect.go, examples/gateway-api/README.md, examples/gateway-api/http-route-with-header-modifiers.yml, examples/gateway-api/http-route-with-request-redirects.yml
see https://gravitee.atlassian.net/browse/GKO-1134
=> feat: implement HTTP Redirect filter

controllers/apim/apidefinition/apidefinitionv2_controller.go, controllers/apim/apidefinition/apidefinitionv4_controller.go, controllers/apim/apidefinition/controller.go, controllers/apim/apidefinition/internal/api_resources.go, controllers/apim/apidefinition/internal/api_shared_policy_groups.go, controllers/apim/apiresource/apiresource_controller.go, controllers/apim/application/application_controller.go, controllers/apim/group/group_controller.go, controllers/apim/ingress/ingress_controller.go, controllers/apim/managementcontext/managementcontext_controller.go, controllers/apim/policygroups/sharedpolicygroups_controller.go, controllers/apim/subscription/subscription_controller.go, internal/admission/template.go, internal/k8s/dynamic/kind.go, internal/k8s/dynamic/resolve.go, internal/predicate/predicate.go, internal/template/compiler.go, internal/template/tree.go, internal/watch/watch.go
see https://gravitee.atlassian.net/browse/GKO-1114
=> fix: update templated resources on source changes

test/integration/apidefinition/v4/update_withContext_changingMemberRole_test.go
see https://gravitee.atlassian.net/browse/GKO-1372
=> ci: skip flaky v4 api member test
